// Action Expressions Syntax Grammar - v1

action = {
	SOI ~ (text | expression | local)* ~ EOI
}

expression_name = { char+ }
expression = {
	"#" ~ "[" ~ expression_name ~ "]" ~ arguments?
}

local = {
	"$" ~ "[" ~ local_name ~ "]"
}
local_name = { char+ }

arguments = {
	"(" ~ (expression | text | "," )* ~ ")"
}

text = { "\"" ~ value ~ "\"" }

value = { (!"\"" ~ ANY)* }
char = _{ ASCII_ALPHANUMERIC | "_" | "-" | "!" }

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
EI = _{ EOI }

